name: 4. Build Docker Image

on:
  workflow_dispatch: # Allows manual trigger via GitHub UI

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest     # Note, 

    steps:
      # Step 1: Clone the repository into the runner
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Build the Docker image using the Dockerfile in the root directory
      - name: Build Docker Image
        run: docker build -t your-image-name:latest .